dist: trusty

services:
  - docker

before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/Dockerfile -t paccmann_rl .

script:
  - docker run -it generator python3 -c "import pytoda"
  - docker run -it generator python3 -c "import paccmann_predictor"
  - docker run -it generator python3 -c "import paccmann_omics"
  - docker run -it generator python3 -c "import paccmann_chemistry"
  - docker run -it generator python3 -c "import paccmann_generator"
