---
name: build
on: [push]
jobs:
  build:
    name: Test env setup (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            pip_cache_path: ~/.cache/pip
            experimental: false
          - os: macos-latest
            pip_cache_path: ~/Library/Caches/pip
            experimental: false
    steps:
      - uses: actions/checkout@v2
      - name: Checkout and setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --no-cache-dir -r requirements.txt
          python3 -c "import pytoda"
          python3 -c "import paccmann_predictor"
          python3 -c "import paccmann_omics"
          python3 -c "import paccmann_chemistry"
          python3 -c "import paccmann_generator"
      - name: Send Slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          text: "CI Build ${{ matrix.os }}"
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
